networks:
  traefik_proxy:
    name: traefik_proxy
    driver: bridge

include:
  - apps/authentik/docker-compose.yaml
  - apps/bazarr/docker-compose.yaml
  - apps/cAdvisor/docker-compose.yaml
  - apps/discord-bot/docker-compose.yaml
  - apps/excalidraw/docker-compose.yaml
  - apps/gd-dyndns/docker-compose.yaml
  - apps/homarr/docker-compose.yaml
#  - apps/home-assistant/docker-compose.yaml
  - apps/jackett/docker-compose.yaml
  - apps/komga/docker-compose.yaml
#  - apps/local-ai/docker-compose.yaml
#  - apps/netdata/docker-compose.yaml
#  - apps/nginx/docker-compose.yaml
#  - apps/minecraft/docker-compose.yaml
  - apps/monitoreo/docker-compose.yaml
  - apps/nextcloud/docker-compose.yaml
  - apps/overseerr/docker-compose.yaml
#  - apps/pihole-dhcp/docker-compose.yaml
  - apps/plex/docker-compose.yaml
  - apps/portainer/docker-compose.yaml
  - apps/qbittorrent/docker-compose.yaml
  - apps/radarr/docker-compose.yaml
  - apps/sonarr/docker-compose.yaml
  - apps/traefik/docker-compose.yaml
  - apps/watchtower/docker-compose.yaml
  - apps/wireguard/docker-compose.yaml
#  - apps/wireguard-pihole/docker-compose.yaml
